# Generated by Django 4.1.5 on 2023-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='post.post'),
        ),
    ]
