# Generated by Django 4.1.5 on 2023-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
