# Generated by Django 4.1.5 on 2023-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_remove_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
