# Generated by Django 4.1.5 on 2023-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0001_initial'),
        ('user', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracks_liked',
            field=models.ManyToManyField(related_name='liked_by', to='track.track'),
        ),
    ]
