# Generated by Django 4.1.5 on 2023-04-01 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
